-- Event Center 初始结构。语句保持幂等，以兼容接入 Flyway 前已经创建的本地数据库。
CREATE TABLE IF NOT EXISTS user_model_profile (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    enabled BOOLEAN NOT NULL,
    provider VARCHAR(64) NOT NULL,
    base_url VARCHAR(512) NOT NULL,
    api_key VARCHAR(512) NOT NULL,
    model VARCHAR(255) NOT NULL,
    temperature DOUBLE,
    max_tokens INT,
    supported_routes VARCHAR(1000) NOT NULL,
    is_default BOOLEAN NOT NULL,
    priority INT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_user_model_profile_user_id (user_id),
    KEY idx_user_model_profile_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS conversation_digest_batch (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    platform VARCHAR(64) NOT NULL,
    chat_type VARCHAR(32) NOT NULL,
    chat_id VARCHAR(255) NOT NULL,
    aggregation_key VARCHAR(512) NOT NULL,
    source_event_ids_json LONGTEXT NOT NULL,
    message_count INT NOT NULL,
    summary LONGTEXT NOT NULL,
    happened LONGTEXT NOT NULL,
    action_items LONGTEXT NOT NULL,
    next_step LONGTEXT NOT NULL,
    period_started_at DATETIME(6),
    period_ended_at DATETIME(6),
    generated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_digest_user_generated (user_id, generated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_record (
    event_id VARCHAR(255) NOT NULL,
    owner_user_id VARCHAR(128) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    received_at DATETIME(6) NOT NULL,
    processing_status VARCHAR(64) NOT NULL,
    processing_summary LONGTEXT NOT NULL,
    resolved_route VARCHAR(128) NOT NULL,
    write_back_status VARCHAR(64) NOT NULL,
    need_human_confirmation BOOLEAN NOT NULL,
    processed_at DATETIME(6),
    reply_draft LONGTEXT NOT NULL,
    execution_trace_json LONGTEXT,
    last_action VARCHAR(64) NOT NULL,
    last_action_note LONGTEXT NOT NULL,
    last_action_at DATETIME(6),
    inbox_status VARCHAR(32) NOT NULL,
    inbox_updated_at DATETIME(6),
    snoozed_until DATETIME(6),
    message_origin VARCHAR(32) NOT NULL,
    PRIMARY KEY (event_id),
    KEY idx_event_record_received_at (received_at),
    KEY idx_event_record_inbox_status (inbox_status),
    KEY idx_event_record_owner_user_id (owner_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_dispatch_retry (
    event_id VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INT NOT NULL,
    next_attempt_at DATETIME(6),
    last_error VARCHAR(2000) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (event_id),
    KEY idx_dispatch_retry_due (status, next_attempt_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_connection (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    platform VARCHAR(64) NOT NULL,
    connector VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL,
    connector_base_url VARCHAR(512) NOT NULL,
    credential_ciphertext VARCHAR(2000) NOT NULL,
    account_id VARCHAR(128) NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    health VARCHAR(32) NOT NULL,
    health_message VARCHAR(1000) NOT NULL,
    last_checked_at DATETIME(6),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_platform_connection_user_id (user_id),
    KEY idx_platform_connection_platform (platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS local_user (
    id VARCHAR(64) NOT NULL,
    username VARCHAR(128) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(1000) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_local_user_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS conversation_profile (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description LONGTEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    platform VARCHAR(64) NOT NULL,
    account_id VARCHAR(128) NOT NULL,
    scene VARCHAR(64) NOT NULL,
    chat_type VARCHAR(64) NOT NULL,
    chat_ids_json LONGTEXT NOT NULL,
    target_user_ids_json LONGTEXT NOT NULL,
    supported_routes_json LONGTEXT NOT NULL,
    trigger_mode VARCHAR(64) NOT NULL,
    trigger_keywords_json LONGTEXT NOT NULL,
    persona_mode VARCHAR(64) NOT NULL,
    system_prompt LONGTEXT NOT NULL,
    skill_reference VARCHAR(1000) NOT NULL,
    skill_references_json LONGTEXT NOT NULL,
    model_profile_id VARCHAR(64) NOT NULL,
    preferred_route VARCHAR(128) NOT NULL,
    reply_mode VARCHAR(64) NOT NULL,
    reply_delay_seconds_min INT,
    reply_delay_seconds_max INT,
    allowed_tools_json LONGTEXT NOT NULL,
    require_human_confirmation BOOLEAN NOT NULL,
    priority INT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    notification_mode VARCHAR(64) NOT NULL,
    notification_keywords_json LONGTEXT NOT NULL,
    digest_window_seconds INT,
    digest_max_messages INT,
    include_urgent_in_digest BOOLEAN NOT NULL,
    max_reply_chars INT NOT NULL,
    split_long_reply BOOLEAN NOT NULL,
    split_reply_chance_percent INT NOT NULL,
    private_history_enabled BOOLEAN NOT NULL,
    history_max_messages INT NOT NULL,
    history_max_chars INT NOT NULL,
    history_training_enabled BOOLEAN NOT NULL,
    review_mode VARCHAR(64) NOT NULL,
    knowledge_base_sources_json LONGTEXT NOT NULL,
    PRIMARY KEY (id),
    KEY idx_conversation_profile_user_id (user_id),
    KEY idx_conversation_profile_match (user_id, enabled, platform, chat_type),
    KEY idx_conversation_profile_priority (priority, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
